### ISSUE TITLE
Create Initial Project Proposal Draft

### ISSUE THREAD

**Issue by sam-mata** [sam-mata/SeaLevelGP#37]
## To-Do:
- [ ] Layout problem statement & motivations.
- [ ] Detail current state of project.
- [ ] Discuss genetic programming techniques as potential improvement.
- [ ] Describe data sources and structures.
- [ ] Outline preprocessing, model architecture, and training stages.
- [ ] Highlight potential for project and results.
- [ ] #33
